hqs = [
    {
        "titulo":"starwars", "edicoes":
        [
            {"id":"sw01", "titulo":"Clássicos 1", "imagem":"star_wars_01_classicos_1.jpg", "comprada":"true"},
            {"id":"sw02", "titulo":"Clássicos 2", "imagem":"star_wars_02_classicos_2.jpg", "comprada":"true"},
            {"id":"sw03", "titulo":"Clássicos 3", "imagem":"star_wars_03_classicos_3.jpg", "comprada":"true"},
            {"id":"sw04", "titulo":"Clássicos 4", "imagem":"star_wars_04_classicos_4.jpg", "comprada":"true"},
            {"id":"sw05", "titulo":"Clássicos 5", "imagem":"star_wars_05_classicos_5.jpg", "comprada":"true"},
            {"id":"sw06", "titulo":"Clássicos 6", "imagem":"star_wars_06_classicos_6.jpg", "comprada":"true"},
            {"id":"sw07", "titulo":"Clássicos 7", "imagem":"star_wars_07_classicos_7.jpg", "comprada":"true"},
            {"id":"sw08", "titulo":"Clássicos 8", "imagem":"star_wars_08_classicos_8.jpg", "comprada":"true"},
            {"id":"sw09", "titulo":"Clássicos 9", "imagem":"star_wars_09_classicos_9.jpg", "comprada":"true"},
            {"id":"sw10", "titulo":"Clássicos 10", "imagem":"star_wars_10_classicos_10.jpg", "comprada":"true"},
            {"id":"sw11", "titulo":"Clássicos 11", "imagem":"star_wars_11_classicos_11.jpg", "comprada":"true"},
            {"id":"sw12", "titulo":"Clássicos 12", "imagem":"star_wars_12_classicos_12.jpg", "comprada":"true"},
            {"id":"sw13", "titulo":"Cavaleiros da Antiga República 1", "imagem":"star_wars_13_cavaleiros_antiga_republica_1.jpg", "comprada":"true"},
            {"id":"sw14", "titulo":"Cavaleiros da Antiga República 2", "imagem":"star_wars_14_cavaleiros_antiga_republica_2.jpg", "comprada":"true"},
            {"id":"sw15", "titulo":"Cavaleiros da Antiga República 3", "imagem":"star_wars_15_cavaleiros_antiga_republica_3.jpg", "comprada":"true"},
            {"id":"sw16", "titulo":"Cavaleiros da Antiga República 4", "imagem":"star_wars_16_cavaleiros_antiga_republica_4.jpg", "comprada":"true"},
            {"id":"sw17", "titulo":"Cavaleiros da Antiga República 5", "imagem":"star_wars_17_cavaleiros_antiga_republica_5.jpg", "comprada":"true"},
            {"id":"sw18", "titulo":"Cavaleiros da Antiga República 6", "imagem":"star_wars_18_cavaleiros_antiga_republica_6.jpg", "comprada":"true"},
            {"id":"sw19", "titulo":"Guerra Iminente", "imagem":"star_wars_19_guerra_iminente.jpg", "comprada":"true"},
            {"id":"sw20", "titulo":"Guerras Clônicas 1", "imagem":"star_wars_20_guerras_clonicas_1.jpg", "comprada":"true"},
            {"id":"sw21", "titulo":"Guerras Clônicas 2", "imagem":"star_wars_21_guerras_clonicas_2.jpg", "comprada":"true"},
            {"id":"sw22", "titulo":"Guerras Clônicas 3", "imagem":"star_wars_22_guerras_clonicas_3.jpg", "comprada":"true"},
            {"id":"sw23", "titulo":"Guerras Clônicas 4", "imagem":"star_wars_23_guerras_clonicas_4.jpg", "comprada":"true"},
            {"id":"sw24", "titulo":"Guerras Clônicas 5", "imagem":"star_wars_24_guerras_clonicas_5.jpg", "comprada":"true"},
            {"id":"sw25", "titulo":"Guerras Clônicas 6", "imagem":"star_wars_25_guerras_clonicas_6.jpg", "comprada":"true"},
            {"id":"sw26", "titulo":"Guerras Clônicas 7", "imagem":"star_wars_26_guerras_clonicas_7.jpg", "comprada":"true"},
            {"id":"sw27", "titulo":"Tempos Sombrios 1", "imagem":"star_wars_27_tempos_sombrios_1.jpg", "comprada":"true"},
            {"id":"sw28", "titulo":"Tempos Sombrios 2", "imagem":"star_wars_28_tempos_sombrios_2.jpg", "comprada":"true"},
            {"id":"sw29", "titulo":"Tempos Sombrios 3", "imagem":"star_wars_29_tempos_sombrios_3.jpg", "comprada":"true"},
            {"id":"sw30", "titulo":"Tempos Sombrios 4", "imagem":"star_wars_30_tempos_sombrios_4.jpg", "comprada":"true"},
            {"id":"sw31", "titulo":"O Poder da Força", "imagem":"star_wars_31_poder_forca.jpg", "comprada":"true"},
            {"id":"sw32", "titulo":"Império 1", "imagem":"star_wars_32_imperio_1.jpg", "comprada":"true"},
            {"id":"sw33", "titulo":"Império 2", "imagem":"star_wars_33_imperio_2.jpg", "comprada":"true"},
            {"id":"sw34", "titulo":"Império 3", "imagem":"star_wars_34_imperio_3.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw35", "titulo":"Império 4", "imagem":"star_wars_35_imperio_4.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw36", "titulo":"Império 5", "imagem":"star_wars_36_imperio_5.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw37", "titulo":"Rebelião 1", "imagem":"star_wars_37_rebeliao_1.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw38", "titulo":"Rebelião 2", "imagem":"star_wars_38_rebeliao_2.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw39", "titulo":"Sombras do Império", "imagem":"star_wars_39_sombras_imperio.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw40", "titulo":"Herdeiro do Império 1", "imagem":"star_wars_40_herdeiro_imperio_1.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw41", "titulo":"Herdeiro do Império 2", "imagem":"star_wars_41_herdeiro_imperio_2.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw42", "titulo":"Império Negro 1", "imagem":"star_wars_42_imperio_negro_1.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw43", "titulo":"Império Negro 2", "imagem":"star_wars_43_imperio_negro_2.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw44", "titulo":"Império Vermelho 1", "imagem":"star_wars_44_imperio_vermelho_1.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw45", "titulo":"Império Vermelho 2", "imagem":"star_wars_45_imperio_vermelho_2.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw46", "titulo":"Academia Jedi", "imagem":"star_wars_46_academia_jedi.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw47", "titulo":"Invasão 1", "imagem":"star_wars_47_invasao_1.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw48", "titulo":"Invasão 2", "imagem":"star_wars_48_invasao_2.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw49", "titulo":"Legado 1", "imagem":"star_wars_49_legado_1.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw50", "titulo":"Legado 2", "imagem":"star_wars_50_legado_2.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw51", "titulo":"Legado 3", "imagem":"star_wars_51_legado_3.jpg", "comprada":"true", "preco":38.99},
            {"id":"sw52", "titulo":"Legado 4", "imagem":"star_wars_52_legado_4.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw53", "titulo":"Legado 5", "imagem":"star_wars_53_legado_5.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw54", "titulo":"Legado 6", "imagem":"star_wars_54_legado_6.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw55", "titulo":"X-Wing:Esquadrão Rebelde 1", "imagem":"star_wars_55_xwing_esquadrao_rebelde_1.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw56", "titulo":"X-Wing:Esquadrão Rebelde 2", "imagem":"star_wars_56_xwing_esquadrao_rebelde_2.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw57", "titulo":"X-Wing:Esquadrão Rebelde 3", "imagem":"star_wars_57_xwing_esquadrao_rebelde_3.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw58", "titulo":"X-Wing:Esquadrão Rebelde 4", "imagem":"star_wars_58_xwing_esquadrao_rebelde_4.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw59", "titulo":"X-Wing:Esquadrão Rebelde 5", "imagem":"star_wars_59_xwing_esquadrao_rebelde_5.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw60", "titulo":"Boba Fett 1", "imagem":"star_wars_60_boba_fett_1.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw61", "titulo":"Boba Fett 2", "imagem":"star_wars_61_boba_fett_2.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw62", "titulo":"Boba Fett 3", "imagem":"star_wars_62_boba_fett_3.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw63", "titulo":"Ascensão dos Sith 1", "imagem":"star_wars_63_darth_maul_1.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw64", "titulo":"Ascensão dos Sith 2", "imagem":"star_wars_64_darth_maul_2.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw65", "titulo":"Droides 1", "imagem":"star_wars_65_droides_1.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw66", "titulo":"Droides 2", "imagem":"star_wars_66_droides_2.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw67", "titulo":"Contos Jedi 1", "imagem":"star_wars_67_contos_jedi_1.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw68", "titulo":"Contos Jedi 2", "imagem":"star_wars_68_contos_jedi_2.jpg", "comprada":"true", "preco":43.99},
            {"id":"sw69", "titulo":"Contos Jedi 3", "imagem":"star_wars_69_contos_jedi_3.jpg", "comprada":"true", "preco":43.99, "original":"Star Wars - Tales of The Jedi - The Freedon Nadd Uprising (1994) 1-2, Star Wars Tales of The Jedi:Dark Lords of The Sith (1994) 1-5"},
            {"id":"sw70", "titulo":"Contos Jedi 4", "imagem":"star_wars_70_contos_jedi_4.jpg", "comprada":"true", "preco":43.99, "original":"Star Wars - Tales of The Jedi - The Sith War (1995) 1-6, Star Wars:Tales of The Jedi - Redemption (1998) 1-5"}
        ]
    },
    {
        "titulo":"graphicnovels", "edicoes":
        [
            {"id":"gnI", "titulo":"Marvel Origens - A Década de 1960", "imagem":"gn_I_marvel_origens_decada_1960.jpg", "comprada":"true", "preco":39.90},
            {"id":"gnII", "titulo":"Thor - Contos de Asgard", "imagem":"gn_II_thor_contos_asgard.jpg", "comprada":"true", "preco":39.90},
            {"id":"gnIII", "titulo":"Doutor Estranho - Uma Terra Sem Nome, Um Tempo Sem Fim", "imagem":"gn_III_doutor_estranho_terra_nome_tempo_fim.jpg", "comprada":"true", "preco":39.90},
            {"id":"gnIV", "titulo":"Quarteto Fantástico - A Vinda de Galactus", "imagem":"gn_IV_quarteto_fantastico_vinda_galactus.jpg", "comprada":"true", "preco":39.90},
            {"id":"gnV", "titulo":"Quarteto Fantástico - O Dia do Juízo Final", "imagem":"gn_V_quarteto_fantastico_dia_juizo_final.jpg", "comprada":"true", "preco":33.36},
            {"id":"gnVI", "titulo":"O Espetacular Homem-Aranha - Homem-Aranha Nunca Mais", "imagem":"gn_VI_espetacular_homem_aranha_nunca_mais.jpg", "comprada":"true", "preco":33.36},
            {"id":"gnVII", "titulo":"O Invencível Homem de Ferro - Tragédia e Triunfo", "imagem":"gn_VII_invencivel_homem_ferro_tragedia_triunfo.jpg", "comprada":"false"},
            {"id":"gnVIII", "titulo":"Nick Fury - Agente da S.H.I.E.L.D. - Parte 1", "imagem":"gn_VIII_nick_fury_agente_shield_1.jpg", "comprada":"false"},
            {"id":"gnIX", "titulo":"Nick Fury - Agente da S.H.I.E.L.D. - Parte 2", "imagem":"gn_IX_nick_fury_agente_shield_2.jpg", "comprada":"false"},
            {"id":"gnX", "titulo":"Os Inumanos", "imagem":"gn_X_inumanos.jpg", "comprada":"false"},
            {"id":"gnXI", "titulo":"O Incrível Hulk - O Monstro Está Solto", "imagem":"gn_XI_incrivel_hulk_monstro_solto.jpg", "comprada":"false"},
            {"id":"gnXII", "titulo":"Vingadores - O Nascimento de Ultron", "imagem":"gn_XII_vingadores_nascimento_ultron.jpg", "comprada":"false"},
            {"id":"gnXIII", "titulo":"O Poderoso Thor - Ragnarok", "imagem":"gn_XIII_poderoso_thor_ragnarok.jpg", "comprada":"false"},
            {"id":"gnXIV", "titulo":"Surfista Prateado - Origens", "imagem":"gn_XIV_surfista_prateado_origens.jpg", "comprada":"false"},
            {"id":"gnXV", "titulo":"X-Men - Crepúsculo dos Mutantes", "imagem":"gn_XV_x_men_crepusculo_mutantes.jpg", "comprada":"false"},
            {"id":"gnXVI", "titulo":"X-Men - À Sombra de Sauron", "imagem":"gn_XVI_x_men_sombra_sauron.jpg", "comprada":"false"},
            {"id":"gnXVII", "titulo":"O Invencível Homem de Ferro - O Início do Fim", "imagem":"gn_XVII_invencivel_homem_ferro_inicio_fim.jpg", "comprada":"false"},
            {"id":"gnXVIII", "titulo":"Marvel Origens - A Década de 1970", "imagem":"gn_XVIII_marvel_origens_decada_1970.jpg", "comprada":"false"},
            {"id":"gnXIX", "titulo":"O Espetacular Homem-Aranha - A Morte dos Stacys", "imagem":"gn_XIX_espetacular_homem_aranha_morte_stacys.jpg", "comprada":"false"},
            {"id":"gnXX", "titulo":"Vingadores - A Guerra Kree-Skrull", "imagem":"gn_XX_vingadores_guerra_kree_skrull.jpg", "comprada":"false"},
            {"id":"gnXXI", "titulo":"Marvel Horror", "imagem":"gn_XXI_marvel_horror.jpg", "comprada":"false"},
            {"id":"gnXXII", "titulo":"Hulk - No Coração do Átomo", "imagem":"gn_XXII_hulk_coracao_atomo.jpg", "comprada":"false"},
            {"id":"gnXXIII", "titulo":"Os Defensores - O Dia dos Defensores", "imagem":"gn_XXIII_defensores_dia_defensores.jpg", "comprada":"false"},
            {"id":"gnXXIV", "titulo":"Vida e Morte do Capitão Marvel - Parte 1", "imagem":"gn_XXIV_vida_morte_capitao_marvel_1.jpg", "comprada":"false"},
            {"id":"gnXXV", "titulo":"Vida e Morte do Capitão Marvel - Parte 2", "imagem":"gn_XXV_vida_morte_capitao_marvel_2.jpg", "comprada":"false"},
            {"id":"gnXXVI", "titulo":"Doutor Estranho - Uma Realidade à Parte", "imagem":"gn_XXVI_doutor_estranho_realidade_parte.jpg", "comprada":"false"},
            {"id":"gnXXVII", "titulo":"A Guerra Vingadores-Defensores", "imagem":"gn_XXVII_guerra_vingadores_defensores.jpg", "comprada":"false"},
            {"id":"gnXXVIII", "titulo":"Pantera Negra - A Fúria do Pantera", "imagem":"gn_XXVIII_pantera_negra_furia_pantera.jpg", "comprada":"false"},
            {"id":"gnXXIX", "titulo":"Howard, O Pato", "imagem":"gn_XXIX_howard_pato.jpg", "comprada":"false"},
            {"id":"gnXXX", "titulo":"Capitão América e Falcão - O Império Secreto", "imagem":"gn_XXX_capitao_america_falcao_imperio_secreto.jpg", "comprada":"false"},
            {"id":"gnXXXI", "titulo":"Deathlok - Origem", "imagem":"gn_XXXI_deathlok_origem.jpg", "comprada":"false"},
            {"id":"gnXXXII", "titulo":"Warlock - Parte 1", "imagem":"gn_XXXII_warlock_1.jpg", "comprada":"false"},
            {"id":"gnXXXIII", "titulo":"Warlock - Parte 2", "imagem":"gn_XXXIII_warlock_2.jpg", "comprada":"false"},
            {"id":"gnXXXIV", "titulo":"Os Fabulosos X-Men - Segunda Gênese", "imagem":"gn_XXXIV_fabulosos_xmen_segunda_genese.jpg", "comprada":"false"},
            {"id":"gnXXXV", "titulo":"Punho de Ferro - A Busca por Collen Wing", "imagem":"gn_XXXV_punho_ferro_busca_collen_wing.jpg", "comprada":"false"},
            {"id":"gnXXXVI", "titulo":"Capitão América e Falcão - A Bomba Enlouquecedora", "imagem":"gn_XXXVI_capitao_america_falcao_bomba_enlouquecedora.jpg", "comprada":"false"},
            {"id":"gnXXXVII", "titulo":"O Que Aconteceria Se... ?", "imagem":"gn_XXXVII_que_aconteceria_se.jpg", "comprada":"false"},
            {"id":"gnXXXVIII", "titulo":"Homem-Aranha - Grandes Encontros Marvel", "imagem":"gn_XXXVIII_homem_aranha_grandes_encontros_marvel.jpg", "comprada":"false"},
            {"id":"gnXXXIX", "titulo":"Os Vingadores - A Saga de Korvac", "imagem":"gn_XXXIX_vingadores_saga_korvac.jpg", "comprada":"false"},
            {"id":"gnXL", "titulo":"Demolidor - Marcado para Morrer", "imagem":"gn_XL_demolidor_marcado_morrer.jpg", "comprada":"false"},
            {"id":"gn01", "titulo":"Homem de Ferro - O Demônio na Garrafa", "imagem":"gn_01_homem_ferro_demonio_garrafa.jpg", "original":"The Invincible Iron Man #120-128", "comprada":"true"},
            {"id":"gn02", "titulo":"Os Fabulosos X-Men - A Saga da Fênix Negra", "imagem":"gn_02_fabulosos_xmen_saga_fenix_negra.jpg", "original":"Uncanny X-Men #129-137", "comprada":"true"},
            {"id":"gn03", "titulo":"Capitão Britânia - O Mundo Distorcido", "imagem":"gn_03_capitao_britania_mundo_distorcido.jpg", "comprada":"true"},
            {"id":"gn04", "titulo":"Eu, Wolverine", "imagem":"gn_04_eu_wolverine.jpg", "comprada":"true"},
            {"id":"gn05", "titulo":"Thor - O Último Viking", "imagem":"gn_05_thor_ultimo_viking.jpg", "comprada":"true", "preco":39.90},
            {"id":"gn06", "titulo":"Guerras Secretas - Parte 1", "imagem":"gn_06_guerras_secretas_1.jpg", "comprada":"true"},
            {"id":"gn07", "titulo":"Guerras Secretas - Parte 2", "imagem":"gn_07_guerras_secretas_2.jpg", "comprada":"true"},
            {"id":"gn08", "titulo":"Demolidor - A Queda de Murdock", "imagem":"gn_08_demolidor_queda_murdock.jpg", "original":"Daredevil #227-233", "comprada":"true"},
            {"id":"gn09", "titulo":"O Espetacular Homem-Aranha - A Última Caçada de Kraven", "imagem":"gn_09_homem_aranha_ultima_cacada_kraven.jpg", "original":"Web of Spider-Man #31-32, Amazing Spider-Man #293-294, Spectacular Spider-Man #131-132", "comprada":"true"},
            {"id":"gn10", "titulo":"O Espetacular Homem-Aranha - O Nascimento de Venom", "imagem":"gn_10_homem_aranha_nascimento_venom.jpg", "original":"The Amazing Spider-Man #252, #256-259, #300, Web of Spider-Man #1", "comprada":"true"},
            {"id":"gn11", "titulo":"O Incrível Hulk - Gritos Silenciosos", "imagem":"gn_11_incrivel_hulk_gritos_silenciosos.jpg", "comprada":"true"},
            {"id":"gn12", "titulo":"Wolverine - Arma X", "imagem":"gn_12_wolverine_arma_x.jpg", "original":"Marvel Comics Presents #72-84", "comprada":"true"},
            {"id":"gn13", "titulo":"Marvels", "imagem":"gn_13_marvels.jpg", "original":"Marvels #0-6", "comprada":"true"},
            {"id":"gn14", "titulo":"Vingadores Eternamente - Parte 1", "imagem":"gn_14_vingadores_eternamente_1.jpg", "comprada":"true"},
            {"id":"gn15", "titulo":"Vingadores Eternamente - Parte 2", "imagem":"gn_15_vingadores_eternamente_2.jpg", "comprada":"true"},
            {"id":"gn16", "titulo":"O Poderoso Thor - Em Busca dos Deuses", "imagem":"gn_16_poderoso_thor_busca_deuses.jpg", "comprada":"true"},
            {"id":"gn17", "titulo":"Demolidor - Diabo da Guarda", "imagem":"gn_17_demolidor_diabo_guarda.jpg", "comprada":"true"},
            {"id":"gn18", "titulo":"Justiceiro - Bem-Vindo de Volta Frank - Parte 1", "imagem":"gn_18_justiceiro_bem_vindo_volta_frank_1.jpg", "comprada":"true"},
            {"id":"gn19", "titulo":"Justiceiro - Bem-Vindo de Volta Frank - Parte 2", "imagem":"gn_19_justiceiro_bem_vindo_volta_frank_2.jpg", "comprada":"true"},
            {"id":"gn20", "titulo":"Ultimate Homem-Aranha - Poder e Responsabilidade", "imagem":"gn_20_ultimate_homem_aranha_poder_responsabilidade.jpg", "comprada":"true"},
            {"id":"gn21", "titulo":"O Espetacular Homem-Aranha - De Volta ao Lar", "imagem":"gn_21_espetacular_homem_aranha_volta_lar.jpg","original":"The Amazing Spider-Man (Vol.2) #30-35", "comprada":"true"},
            {"id":"gn22", "titulo":"O Espetacular Homem-Aranha - Revelações & Até que as Estrelas Esfriem", "imagem":"gn_22_espetacular_homem_aranha_revelacoes_estrelas_esfriem.jpg", "comprada":"true"},
            {"id":"gn23", "titulo":"Novos X-Men - E de Extinção", "imagem":"gn_23_novos_xmen_e_extincao.jpg", "comprada":"true"},
            {"id":"gn24", "titulo":"Novos X-Men - Imperial", "imagem":"gn_24_novos_xmen_imperial.jpg", "comprada":"true"},
            {"id":"gn25", "titulo":"Homem-Aranha - Azul", "imagem":"gn_25_homem_aranha_azul.jpg", "comprada":"true"},
            {"id":"gn26", "titulo":"Wolverine - Origem", "imagem":"gn_26_wolverine_origem.jpg", "comprada":"true"},
            {"id":"gn27", "titulo":"Capitão América - O Novo Pacto", "imagem":"gn_27_capitao_america_novo_pacto.jpg", "original":"Captain America (Vol.4) #1-6", "comprada":"true"},
            {"id":"gn28", "titulo":"Os Supremos - Super-Humanos", "imagem":"gn_28_supremos_super_humano.jpg", "comprada":"true"},
            {"id":"gn29", "titulo":"Os Supremos - Segurança Nacional", "imagem":"gn_29_supremos_seguranca_nacional.jpg", "comprada":"true"},
            {"id":"gn30", "titulo":"Quarteto Fantástico - Inconcebível", "imagem":"gn_30_quarteto_fantastico_inconcebivel.jpg", "comprada":"true"},
            {"id":"gn31", "titulo":"Quarteto Fantástico - Ações Autoritárias", "imagem":"gn_31_quarteto_fantastico_acoes_autoritarias.jpg", "comprada":"true"},
            {"id":"gn32", "titulo":"1602", "imagem":"gn_32_1602.jpg", "comprada":"true"},
            {"id":"gn33", "titulo":"Guerra Secreta", "imagem":"gn_33_guerra_secreta.jpg", "comprada":"true"},
            {"id":"gn34", "titulo":"Vingadores - A Queda", "imagem":"gn_34_vingadores_queda.jpg", "original":"Avengers #500-503, Avengers Finale", "comprada":"true"},
            {"id":"gn35", "titulo":"Mulher-Hulk - Mulher Solteira Procura", "imagem":"gn_35_mulher_hulk_mulher_solteira_procura.jpg", "comprada":"true"},
            {"id":"gn36", "titulo":"Surpreendentes X-Men - Superdotados", "imagem":"gn_36_surpreendentes_xmen_superdotados.jpg", "original":"Astonishing X-Men #1-6", "comprada":"true"},
            {"id":"gn37", "titulo":"Os Surpreendentes X-Men - Perigoso", "imagem":"gn_37_surpreendentes_xmen_perigoso.jpg", "comprada":"true"},
            {"id":"gn38", "titulo":"Pantera Negra - Quem é o Pantera Negra?", "imagem":"gn_38_pantera_negra_quem_pantera_negra.jpg", "original":"Black Panther (Vol.4) #1-6", "comprada":"true"},
            {"id":"gn39", "titulo":"Motoqueiro Fantasma - Estrada para a Danação", "imagem":"gn_39_motoqueiro_fantasma_estrada_danacao.jpg", "comprada":"true"},
            {"id":"gn40", "titulo":"Dinastia M", "imagem":"gn_40_dinastia_m.jpg", "comprada":"true"},
            {"id":"gn41", "titulo":"Dinastia M - O Herdeiro", "imagem":"gn_41_dinastia_m_herdeiro.jpg", "comprada":"true"},
            {"id":"gn42", "titulo":"Os Novos Vingadores - Motim", "imagem":"gn_42_novos_vingadores_motim.jpg", "comprada":"true"},
            {"id":"gn43", "titulo":"Homem de Ferro - Extremis", "imagem":"gn_43_homem_ferro_extremis.jpg", "comprada":"true"},
            {"id":"gn44", "titulo":"Capitão América - Tempo Esgotado", "imagem":"gn_44_capitao_america_tempo_esgotado.jpg", "comprada":"true"},
            {"id":"gn45", "titulo":"Capitão América - Soldado Invernal", "imagem":"gn_45_capitao_america_soldado_invernal.jpg", "comprada":"true"},
            {"id":"gn46", "titulo":"O Incrível Hulk - Planeta Hulk - Parte 1", "imagem":"gn_46_incrivel_hulk_planeta_hulk_1.jpg", "comprada":"true"},
            {"id":"gn47", "titulo":"O Incrível Hulk - Planeta Hulk - Parte 2", "imagem":"gn_47_incrivel_hulk_planeta_hulk_2.jpg", "comprada":"true"},
            {"id":"gn48", "titulo":"Quarteto Fantástico - O Fim", "imagem":"gn_48_quarteto_fantastico_fim.jpg", "original":"Fantastic Four: The End #1-6", "comprada":"true"},
            {"id":"gn49", "titulo":"Zumbis Marvel", "imagem":"gn_49_zumbis_marvel.jpg", "comprada":"true"},
            {"id":"gn50", "titulo":"Guerra Civil", "imagem":"gn_50_guerra_civil.jpg", "comprada":"true"},
            {"id":"gn51", "titulo":"Capitão América - Morre uma Lenda", "imagem":"gn_51_capitao_america_morre_lenda.jpg", "original":"Captain America #25, Fallen Son #1-5", "comprada":"true"},
            {"id":"gn52", "titulo":"Thor - O Renascer dos Deuses", "imagem":"gn_52_thor_renascer_deuses.jpg", "original":"Thor (Vol.3) #1-6", "comprada":"true"},
            {"id":"gn53", "titulo":"Doutor Estranho - O Juramento", "imagem":"gn_53_doutor_estranho_juramento.jpg", "original":"Doctor Strange: The Oath #1-5", "comprada":"true"},
            {"id":"gn54", "titulo":"Eternos", "imagem":"gn_54_eternos.jpg", "original":"Eternals #1-7", "comprada":"true"},
            {"id":"gn55", "titulo":"Capitão América - A Escolha", "imagem":"gn_55_capitao_america_escolha.jpg", "comprada":"true"},
            {"id":"gn56", "titulo":"Hulk - Contra o Mundo", "imagem":"gn_56_hulk_contra_mundo.jpg", "original":"World War Hulk #1-5", "comprada":"true"},
            {"id":"gn57", "titulo":"Thunderbolts - Fé em Monstros", "imagem":"gn_57_thunderbolts_fe_monstros.jpg", "original":"Thunderbolts #110-115, Civil War: Choosing Sides", "comprada":"true"},
            {"id":"gn58", "titulo":"Wolverine - O Velho Logan", "imagem":"gn_58_wolverine_velho_logan.jpg", "original":"Wolverine (Vol.3) #66-72 e Wolverine: Giant-Size Old Man Logan", "comprada":"true"},
            {"id":"gn59", "titulo":"Invasão Secreta", "imagem":"gn_59_invasao_secreta.jpg", "comprada":"true"},
            {"id":"gn60", "titulo":"O Cerco", "imagem":"gn_60_cerco.jpg", "comprada":"true", "preco":39.90},
            {"id":"gn61", "titulo":"Vingadores Primordiais", "imagem":"gn_61_vingadores_primordiais.jpg", "comprada":"true", "preco":39.90},
            {"id":"gn62", "titulo":"Vingadores Secretos - Missão Marte", "imagem":"gn_62_vingadores_secretos_missao_marte.jpg", "comprada":"true", "preco":39.90},
            {"id":"gn63", "titulo":"Deadpool - A Guerra de Wade Wilson", "imagem":"gn_63_deadpool_guerra_wade_wilson.jpg", "comprada":"true", "preco":39.90},
            {"id":"gn64", "titulo":"O Imperativo Thanos", "imagem":"gn_64_imperativo_thanos.jpg", "comprada":"true", "preco":33.36},
            {"id":"gn65", "titulo":"Terra das Sombras", "imagem":"gn_65_terra_sombras.jpg", "comprada":"false"},
            {"id":"gn66", "titulo":"Vingadores - A Cruzada das Crianças", "imagem":"gn_66_vingadores_cruzada_criancas.jpg", "comprada":"false"},
            {"id":"gn67", "titulo":"Hulk - Terra Arrasada", "imagem":"gn_67_hulk_terra_arrasada.jpg", "comprada":"false"},
            {"id":"gn68", "titulo":"Venom", "imagem":"gn_68_venom.jpg", "comprada":"false"},
            {"id":"gn69", "titulo":"Homem-Aranha - A Morte do Homem-Aranha", "imagem":"gn_69_homem_aranha_morte_homem_aranha.jpg", "comprada":"false"},
            {"id":"gn70", "titulo":"A Essência do Medo - Parte 1", "imagem":"gn_70_essencia_medo_1.jpg", "comprada":"false"},
            {"id":"gn71", "titulo":"A Essência do Medo - Parte 2", "imagem":"gn_71_essencia_medo_2.jpg", "comprada":"false"},
            {"id":"gn72", "titulo":"X-Men - O Cisma", "imagem":"gn_72_x_men_cisma.jpg", "comprada":"false"},
            {"id":"gn73", "titulo":"Demolidor - Som e Fúria", "imagem":"gn_73_demolidor_som_furia.jpg", "comprada":"false"},
            {"id":"gn74", "titulo":"Ultimate Comics Homem-Aranha - Quem é Miles Morales?", "imagem":"gn_74_ultimate_comics_homem_aranha_quem_miles_morales.jpg", "comprada":"false"},
            {"id":"gn75", "titulo":"O Surpreendente Thor", "imagem":"gn_75_surpreendente_thor.jpg", "comprada":"false"},
            {"id":"gn76", "titulo":"Sem Medo", "imagem":"gn_76_sem_medo.jpg", "comprada":"false"},
            {"id":"gn77", "titulo":"Sem Medo - Parte 2", "imagem":"gn_77_sem_medo_2.jpg", "comprada":"false"},
            {"id":"gn78", "titulo":"Aniquiladores", "imagem":"gn_78_aniquiladores.jpg", "comprada":"false"},
            {"id":"gn79", "titulo":"O Incrível Hulk - Abissal", "imagem":"gn_79_incrivel_hulk_abissal.jpg", "comprada":"false"},
            {"id":"gn80", "titulo":"Wolverine & Os X-Men - Regênese", "imagem":"gn_80_wolverine_x-men_regenese.jpg", "comprada":"false"},
            {"id":"gn81", "titulo":"Os Defensores - O Destruidor de Mundos", "imagem":"gn-81-defensores-destruidor-mundos.jpg", "comprada":"false", "original":"Marvel Point One #1, The Defenders (Vol.4) #1-6 (2012)"},
            {"id":"gn82", "titulo":"Avante, Vingadores!", "imagem":"gn-82-avante-vingadores.jpg", "comprada":"false", "original":"Avengers Assemble #1-8 (2012)"},
            {"id":"gn83", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn84", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn85", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn86", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn87", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn88", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn89", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn90", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn91", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn92", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn93", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn94", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn95", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn96", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn97", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn98", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn99", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn100", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn101", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn102", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn103", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn104", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn105", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn106", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn107", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn108", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn109", "titulo":"", "imagem":"gn_", "comprada":"false"},
            {"id":"gn110", "titulo":"", "imagem":"gn_", "comprada":"false"}
        ]
    },
    {
        "titulo":"dc", "edicoes":
        [
            {"id":"dc01", "titulo":"Batman - Silêncio - Parte 1", "imagem":"dc_01_batman_silencio_1.jpg", "comprada":"true"},
            {"id":"dc02", "titulo":"Batman - Silêncio - Parte 2", "imagem":"dc_02_batman_silencio_2.jpg", "comprada":"true"},
            {"id":"dc03", "titulo":"Superman - O Último Filho", "imagem":"dc_03_superman_ultimo_filho.jpg", "comprada":"true"},
            {"id":"dc04", "titulo":"Liga da Justiça - Torre de Babel", "imagem":"dc_04_liga_justica_torre_babel.jpg", "comprada":"true", "preco":39.99},
            {"id":"dc05", "titulo":"Superman/Batman - Inimigos Públicos", "imagem":"dc_05_superman_batman_inimigos_publicos.jpg", "comprada":"true", "preco":39.99},
            {"id":"dc06", "titulo":"Batman - O Longo Dia das Bruxas - Parte 1", "imagem":"dc_06_batman_longo_dia_bruxas_1.jpg", "comprada":"true", "preco":39.99},
            {"id":"dc07", "titulo":"Batman - O Longo Dia das Bruxas - Parte 2", "imagem":"dc_07_batman_longo_dia_bruxas_2.jpg", "comprada":"true", "preco":39.99},
            {"id":"dc08", "titulo":"Superman - O Homem de Aço", "imagem":"dc_08_superman_homem_aco.jpg", "comprada":"true", "preco":39.99},
            {"id":"dc09", "titulo":"LJA - Ano Um - Parte 1", "imagem":"dc_09_lja_ano_um_1.jpg", "comprada":"true", "preco":39.99},
            {"id":"dc10", "titulo":"LJA - Ano Um - Parte 2", "imagem":"dc_10_lja_ano_um_2.jpg", "comprada":"true", "preco":44.00},
            {"id":"dc11", "titulo":"Batman - Morte em Família", "imagem":"dc_11_batman_morte_familia.jpg", "comprada":"true", "preco":39.99},
            {"id":"dc12", "titulo":"Lex Luthor - O Homem de Aço", "imagem":"dc_12_lex_luthor_homem_aco.jpg", "comprada":"true", "preco":40.00},
            {"id":"dc13", "titulo":"LJA - Terra 2", "imagem":"dc_13_lja_terra_2.jpg", "comprada":"true", "preco":39.99},
            {"id":"dc14", "titulo":"Superman/Batman - Supergirl", "imagem":"dc_14_superman_batman_supergirl.jpg", "comprada":"false"},
            {"id":"dc15", "titulo":"Batman - O Nascimento do Demônio - Parte 1", "imagem":"dc_15_batman_nascimento_demonio_1.jpg", "comprada":"false"},
            {"id":"dc16", "titulo":"Batman - O Nascimento do Demônio - Parte 2", "imagem":"dc_16_batman_nascimento_demonio_2.jpg", "comprada":"false"},
            {"id":"dc17", "titulo":"Mulher Maravilha - O Círculo", "imagem":"dc_17_mulher_maravilha_circulo.jpg", "comprada":"false"},
            {"id":"dc18", "titulo":"Superman - Brainiac", "imagem":"dc_18_superman_brainiac.jpg", "comprada":"false"},
            {"id":"dc19", "titulo":"LJA - O Prego", "imagem":"dc_19_lja_prego.jpg", "comprada":"false"},
            {"id":"dc20", "titulo":"Novos Titãs - O Contrato de Judas", "imagem":"dc_20_novos_titas_contrato_judas.jpg", "comprada":"false"},
            {"id":"dc21", "titulo":"Mulher-Maravilha, Batman e Superman - Trindade", "imagem":"dc_21_mulher_maravilha_batman_superman_trindade.jpg", "comprada":"false"},
            {"id":"dc22", "titulo":"Mulher-Gato - Um Crime Perfeito", "imagem":"dc_22_mulher_gato_crime_perfeito.jpg", "comprada":"false"},
            {"id":"dc23", "titulo":"Mulher-Gato - A Trilha da Mulher-Gato", "imagem":"dc_23_mulher_gato_trilha.jpg", "comprada":"false"},
            {"id":"dc24", "titulo":"Superman - A Morte do Superman", "imagem":"dc_24_superman_morte_superman.jpg", "comprada":"false"},
            {"id":"dc25", "titulo":"Lobo - Sem Limites", "imagem":"dc_25_lobo_sem_limites.jpg", "comprada":"false"},
            {"id":"dc26", "titulo":"Mulher-Maravilha - Paraíso Perdido", "imagem":"dc_26_mulher_maravilha_paraiso_perdido.jpg", "comprada":"false"},
            {"id":"dc27", "titulo":"LJA - Justiça - Parte 1", "imagem":"dc_27_lja_justica_1.jpg", "comprada":"false"},
            {"id":"dc28", "titulo":"LJA - Justiça - Parte 2", "imagem":"dc_28_lja_justica_2.jpg", "comprada":"false"},
            {"id":"dc29", "titulo":"Superman e Batman - Poder Absoluto", "imagem":"dc_29_superman_batman_poder_absoluto.jpg", "comprada":"false"},
            {"id":"dc30", "titulo":"Lanterna Verde - Crepúsculo Esmeralda/Novo Amanhecer", "imagem":"dc_30_lanterna_verde_crepusculo_esmeralda_novo_amanhecer.jpg", "comprada":"false"},
            {"id":"dc31", "titulo":"Arlequina - Prelúdios e Trocadalhos", "imagem":"dc_31_arlequina_preludios_trocadalhos.jpg", "comprada":"true", "preco":23.47},
            {"id":"dc32", "titulo":"Arqueiro Verde - O Espírito da Flecha - Parte 1", "imagem":"dc_32_arqueiro_verde_espirito_flecha_1.jpg", "comprada":"false"},
            {"id":"dc33", "titulo":"Arqueiro Verde - O Espírito da Flecha - Parte 2", "imagem":"dc_33_arqueiro_verde_espirito_flecha_2.jpg", "comprada":"false"},
            {"id":"dc34", "titulo":"Batman - O Homem que ri & Asilo Arkham", "imagem":"dc_34_batman_homem_que_ri_asilo_arkham.jpg", "comprada":"true", "preco":23.47},
            {"id":"dc35", "titulo":"DC - A Nova Fronteira - Parte 1", "imagem":"dc_35_dc_nova_fronteira_1.jpg", "comprada":"false"},
            {"id":"dc36", "titulo":"DC - A Nova Fronteira - Parte 2", "imagem":"dc_36_dc_nova_fronteira_2.jpg", "comprada":"false"},
            {"id":"dc37", "titulo":"Superman e Batman - Vingança Máxima!", "imagem":"dc_37_superman_batman_vinganca_maxima.jpg", "comprada":"true", "preco":23.47},
            {"id":"dc38", "titulo":"Mulher Maravilha - Deuses e Mortais", "imagem":"dc_38_mulher_maravilha_deuses_mortais.jpg", "comprada":"false"},
            {"id":"dc39", "titulo":"Batman - Estranhas Aparições", "imagem":"dc_39_batman_estranhas_aparicoes.jpg", "comprada":"false"},
            {"id":"dc40", "titulo":"Superman & Batman - Inimigos Entre Nós", "imagem":"dc_40_superman_batman_inimigos_entre_nos.jpg", "comprada":"false"},
            {"id":"dc41", "titulo":"Arqueiro Verde - Ano Um", "imagem":"dc_41_arqueiro_verde_ano_um.jpg", "comprada":"false"},
            {"id":"dc42", "titulo":"Batman - Sina Macabra", "imagem":"dc_42_sina_macabra.jpg", "comprada":"false"},
            {"id":"dc43", "titulo":"Batman - Descanse em Paz", "imagem":"", "comprada":"false"},
            {"id":"dc44", "titulo":"Flash - Nascido para Correr", "imagem":"dc_44_flash_nascido_correr.jpg", "comprada":"false"},
            {"id":"dc45", "titulo":"Robin - Ano Um", "imagem":"dc_45_robin_ano_um.jpg", "comprada":"false"},
            {"id":"dc46", "titulo":"Superman/Batman - Tormento", "imagem":"dc_46_superman_batman_tormento.jpg", "comprada":"false"},
            {"id":"dc47", "titulo":"Mulher-Maravilha - Os Olhos da Górgona", "imagem":"dc_47_mulher_maravilha_olhos_gorgona.jpg", "comprada":"false"},
            {"id":"dc48", "titulo":"Batgirl - Ano Um", "imagem":"dc_48_batgirl_ano_um.jpg", "comprada":"false"},
            {"id":"dc49", "titulo":"Justiça Jovem - Uma Nova Liga", "imagem":"dc_49_justica_jovem_nova_liga.jpg", "comprada":"true", "preco":23.47},
            {"id":"dc50", "titulo":"Flash - O Retorno de Barry Allen", "imagem":"dc_50_flash_retorno_barry_allen.jpg", "comprada":"false"},
            {"id":"dc51", "titulo":"Batman - Amantes e Loucos", "imagem":"dc_51_batman_amantes_loucos.jpg", "comprada":"false"},
            {"id":"dc52", "titulo":"Arqueiro Verde - Os Caçadores", "imagem":"dc_52_arqueiro_verde_cacadores.jpg", "comprada":"false"},
            {"id":"dc53", "titulo":"O Bravo e o Audaz - Os Donos da Sorte", "imagem":"dc_53_bravo_audaz_donos_sorte.jpg", "comprada":"false"},
            {"id":"dc54", "titulo":"Homem-Borracha - Uma Caçada Muito Louca", "imagem":"dc_54_homem_borracha_cacada_muito_louca.jpg", "comprada":"false"},
            {"id":"dc55", "titulo":"LJA - Nova Ordem Mundial", "imagem":"dc_55_lja_nova_ordem_mundial.jpg", "comprada":"false"},
            {"id":"dc56", "titulo":"Flash - Guerra de Gangues", "imagem":"dc_56_flash_guerra_gangues.jpg", "comprada":"false"},
            {"id":"dc57", "titulo":"Superman - O Legado das Estrelas - Parte 1", "imagem":"dc_57_superman_legado_estrelas_1.jpg", "comprada":"false"},
            {"id":"dc58", "titulo":"Superman - O Legado das Estrelas - Parte 2", "imagem":"dc_58_superman_legado_estrelas_2.jpg", "comprada":"false"},
            {"id":"dc59", "titulo":"Arqueiro Verde e Lanterna Verde - Na Estrada", "imagem":"dc_59_arqueiro_lanterna_estrada.jpg", "comprada":"false"},
            {"id":"dc60", "titulo":"Flash - Ponto de Ignição", "imagem":"dc_60_flash_ponto_ignicao.jpg", "comprada":"false"},
            {"id":"dc61", "titulo":"Batman/Caçadora - Sede de Sangue", "imagem":"dc_61_batman_cacadora_sede_sangue.jpg", "comprada":"false"},
            {"id":"dc62", "titulo":"LJA - Desígnios Divinos", "imagem":"dc_62_lja_designios_divinos.jpg", "comprada":"false"},
            {"id":"dc63", "titulo":"Superman - O que Aconteceu ao Homem de Aço?", "imagem":"dc_63_superman_que_aconteceu_homem_aco.jpg", "comprada":"false"},
            {"id":"dc64", "titulo":"LJA/ SJA - Vícios e Virtudes", "imagem":"dc_64_lja_sja_vicios_virtudes.jpg", "comprada":"false"},
            {"id":"dc65", "titulo":"65", "imagem":"", "comprada":"false"},
            {"id":"dc66", "titulo":"66", "imagem":"", "comprada":"false"},
            {"id":"dc67", "titulo":"67", "imagem":"", "comprada":"false"},
            {"id":"dc68", "titulo":"68", "imagem":"", "comprada":"false"},
            {"id":"dc69", "titulo":"69", "imagem":"", "comprada":"false"},
            {"id":"dc70", "titulo":"70", "imagem":"", "comprada":"false"},
            {"id":"dc71", "titulo":"71", "imagem":"", "comprada":"false"},
            {"id":"dc72", "titulo":"72", "imagem":"", "comprada":"false"},
            {"id":"dc73", "titulo":"73", "imagem":"", "comprada":"false"},
            {"id":"dc74", "titulo":"74", "imagem":"", "comprada":"false"},
            {"id":"dc75", "titulo":"75", "imagem":"", "comprada":"false"},
            {"id":"dc76", "titulo":"76", "imagem":"", "comprada":"false"},
            {"id":"dc77", "titulo":"77", "imagem":"", "comprada":"false"},
            {"id":"dc78", "titulo":"78", "imagem":"", "comprada":"false"},
            {"id":"dc79", "titulo":"79", "imagem":"", "comprada":"false"},
            {"id":"dc80", "titulo":"80", "imagem":"", "comprada":"false"},
            {"id":"dc81", "titulo":"81", "imagem":"", "comprada":"false"},
            {"id":"dc82", "titulo":"82", "imagem":"", "comprada":"false"},
            {"id":"dc83", "titulo":"83", "imagem":"", "comprada":"false"},
            {"id":"dc84", "titulo":"84", "imagem":"", "comprada":"false"},
            {"id":"dc85", "titulo":"85", "imagem":"", "comprada":"false"},
            {"id":"dc86", "titulo":"86", "imagem":"", "comprada":"false"},
            {"id":"dc87", "titulo":"87", "imagem":"", "comprada":"false"},
            {"id":"dc88", "titulo":"88", "imagem":"", "comprada":"false"},
            {"id":"dc89", "titulo":"89", "imagem":"", "comprada":"false"},
            {"id":"dc90", "titulo":"90", "imagem":"", "comprada":"false"},
            {"id":"dc91", "titulo":"91", "imagem":"", "comprada":"false"},
            {"id":"dc92", "titulo":"92", "imagem":"", "comprada":"false"},
            {"id":"dc93", "titulo":"93", "imagem":"", "comprada":"false"},
            {"id":"dc94", "titulo":"94", "imagem":"", "comprada":"false"},
            {"id":"dc95", "titulo":"95", "imagem":"", "comprada":"false"},
            {"id":"dc96", "titulo":"96", "imagem":"", "comprada":"false"},
            {"id":"dc97", "titulo":"97", "imagem":"", "comprada":"false"},
            {"id":"dc98", "titulo":"98", "imagem":"", "comprada":"false"},
            {"id":"dc99", "titulo":"99", "imagem":"", "comprada":"false"},
            {"id":"dc100", "titulo":"100", "imagem":"", "comprada":"false"}
        ]
    },
    {
        "titulo":"herois", "edicoes":
        [
            {"id":"he01", "titulo":"Os Vingadores", "imagem":"he_01_vingadores.jpg", "comprada":"true"},
            {"id":"he02", "titulo":"Homem-Aranha", "imagem":"he_02_homem_aranha.jpg", "comprada":"true"},
            {"id":"he03", "titulo":"Wolverine", "imagem":"he_03_wolverine.jpg", "comprada":"true"},
            {"id":"he04", "titulo":"Hulk", "imagem":"he_04_hulk.jpg", "comprada":"true"},
            {"id":"he05", "titulo":"Homem de Ferro", "imagem":"he_05_homem_ferro.jpg", "comprada":"true"},
            {"id":"he06", "titulo":"Viúva-Negra", "imagem":"he_06_viuva_negra.jpg", "comprada":"true"},
            {"id":"he07", "titulo":"Capitão América", "imagem":"he_07_capitao_america.jpg", "comprada":"true"},
            {"id":"he08", "titulo":"Tocha Humana", "imagem":"he_08_tocha_humana.jpg", "comprada":"true"},
            {"id":"he09", "titulo":"Gavião Arqueiro", "imagem":"he_09_gaviao_arqueiro.jpg", "comprada":"true"},
            {"id":"he10", "titulo":"X-Men", "imagem":"he_10_x_men.jpg", "comprada":"true"},
            {"id":"he11", "titulo":"Luke Cage", "imagem":"he_11_luke_cage.jpg", "comprada":"true"},
            {"id":"he12", "titulo":"Os Três Guerreiros", "imagem":"he_12_tres_guerreiros.jpg", "comprada":"true"},
            {"id":"he13", "titulo":"Ciclope", "imagem":"he_13_ciclope.jpg", "comprada":"true"},
            {"id":"he14", "titulo":"Capitão Marvel", "imagem":"he_14_capitao_marvel.jpg", "comprada":"true"},
            {"id":"he15", "titulo":"Os Fabulosos X-Men", "imagem":"he_15_fabulosos_xmen.jpg", "comprada":"true"},
            {"id":"he16", "titulo":"A Mulher Invisível", "imagem":"he_16_mulher_invisivel.jpg", "comprada":"true"},
            {"id":"he17", "titulo":"Visão", "imagem":"he_17_visao.jpg", "comprada":"true"},
            {"id":"he18", "titulo":"Guardiões da Galáxia", "imagem":"he_18_guardioes_galaxia.jpg", "comprada":"true"},
            {"id":"he19", "titulo":"Falcão", "imagem":"he_19_falcao.jpg", "comprada":"true"},
            {"id":"he20", "titulo":"Namor - O Príncipe Submarino", "imagem":"he_20_namor.jpg", "comprada":"true", "preco":39.90},
            {"id":"he21", "titulo":"Valquíria", "imagem":"he_21_valquiria.jpg", "comprada":"true", "preco":39.90},
            {"id":"he22", "titulo":"Professor X", "imagem":"he_22_professor_x.jpg", "comprada":"true", "preco":39.90},
            {"id":"he23", "titulo":"Defensores", "imagem":"he_23_defensores.jpg", "comprada":"true", "preco":39.90},
            {"id":"he24", "titulo":"Justiceiro", "imagem":"he_24_justiceiro.jpg", "comprada":"true", "preco":39.90},
            {"id":"he25", "titulo":"Nick Fury", "imagem":"he_25_nick_fury.jpg", "comprada":"true", "preco":39.90},
            {"id":"he26", "titulo":"Pantera Negra", "imagem":"he_26_pantera_negra.jpg", "comprada":"true", "preco":39.90},
            {"id":"he27", "titulo":"Madrox - O Homem Múltiplo", "imagem":"he_27_madrox.jpg", "comprada":"true", "preco":39.90},
            {"id":"he28", "titulo":"Harpia", "imagem":"he_28_harpia.jpg", "comprada":"true", "preco":39.90},
            {"id":"he29", "titulo":"Demolidor", "imagem":"he_29_demolidor.jpg", "comprada":"true", "preco":33.36},
            {"id":"he30", "titulo":"Quarteto Fantástico", "imagem":"he_30_quarteto_fantastico.jpg", "comprada":"true", "preco":33.36},
            {"id":"he31", "titulo":"Doutor Estranho", "imagem":"he_31_doutor_estranho.jpg", "comprada":"true", "preco":33.36},
            {"id":"he32", "titulo":"O Coisa", "imagem":"he_32_o_coisa.jpg", "comprada":"true", "preco":33.36},
            {"id":"he33", "titulo":"Destrutor", "imagem":"he_33_destrutor.jpg", "comprada":"true", "preco":33.36},
            {"id":"he34", "titulo":"Feiticeira Escarlate", "imagem":"he_34_feiticeira_escarlate.jpg", "comprada":"false"},
            {"id":"he35", "titulo":"O Anjo", "imagem":"he_35_anjo.jpg", "comprada":"false"},
            {"id":"he36", "titulo":"Punho de Ferro", "imagem":"he_36_punho_ferro.jpg", "comprada":"false"},
            {"id":"he37", "titulo":"Mercúrio", "imagem":"he_37_mercurio.jpg", "comprada":"false"},
            {"id":"he38", "titulo":"Blade", "imagem":"he_38_blade.jpg", "comprada":"false"},
            {"id":"he39", "titulo":"Inumanos", "imagem":"he_39_inumanos.jpg", "comprada":"false"},
            {"id":"he40", "titulo":"Fera", "imagem":"he_40_fera.jpg", "comprada":"false"},
            {"id":"he41", "titulo":"Thor", "imagem":"he_41_thor.jpg", "comprada":"false"},
            {"id":"he42", "titulo":"Shang-Chi", "imagem":"he_42_shang_chi.jpg", "comprada":"false"},
            {"id":"he43", "titulo":"Polaris", "imagem":"he_43_polaris.jpg", "comprada":"false"},
            {"id":"he44", "titulo":"Warlock", "imagem":"he_44_warlock.jpg", "comprada":"false"},
            {"id":"he45", "titulo":"Hank Pym", "imagem":"he_45_hank_pym.jpg", "comprada":"false"},
            {"id":"he46", "titulo":"Hércules", "imagem":"he_46_hercules.jpg", "comprada":"false"},
            {"id":"he47", "titulo":"Homem de Gelo", "imagem":"he_47_homem_de_gelo.jpg", "comprada":"false"},
            {"id":"he48", "titulo":"Vespa", "imagem":"he_48_vespa.jpg", "comprada":"false"},
            {"id":"he49", "titulo":"Motoqueiro Fantasma", "imagem":"he_49_motoqueiro_fantasma.jpg", "comprada":"false"},
            {"id":"he50", "titulo":"Magnum", "imagem":"he_50_magnum.jpg", "comprada":"false"},
            {"id":"he51", "titulo":"Surfista Prateado", "imagem":"he_51_surfista_prateado.jpg", "comprada":"false"},
            {"id":"he52", "titulo":"Banshee", "imagem":"he_52_banshee.jpg", "comprada":"false"},
            {"id":"he53", "titulo":"Cavaleiro Negro", "imagem":"he_53_cavaleiro_negro.jpg", "comprada":"false"},
            {"id":"he54", "titulo":"Tempestade", "imagem":"he_54_tempestade.jpg", "comprada":"false"},
            {"id":"he55", "titulo":"Tocha Humana (Johnny Storm)", "imagem":"he_55_tocha_humana_johnny_strom.jpg", "comprada":"false"},
            {"id":"he56", "titulo":"Colossus", "imagem":"he_56_colossus.jpg", "comprada":"false"},
            {"id":"he57", "titulo":"Senhor Fantástico", "imagem":"he_57_senhor_fantastico.jpg", "comprada":"false"},
            {"id":"he58", "titulo":"Noturno", "imagem":"he_58_noturno.jpg", "comprada":"false"},
            {"id":"he59", "titulo":"Jean Grey", "imagem":"he_59_jean_grey.jpg", "comprada":"false"},
            {"id":"he60", "titulo":"Miss Marvel", "imagem":"he_60_miss_marvel.jpg", "comprada":"false"},
            {"id":"he61", "titulo":"Deadpool", "imagem":"he_61_deadpool.jpg", "comprada":"false"},
            {"id":"he62", "titulo":"Soldado Invernal", "imagem":"he_62_soldado_invernal.jpg", "comprada":"false"},
            {"id":"he63", "titulo":"Elektra", "imagem":"he_63_elektra.jpg", "comprada":"false"},
            {"id":"he64", "titulo":"Jessica Jones", "imagem":"he_64_jessica_jones.jpg", "comprada":"false"},
            {"id":"he65", "titulo":"Máquina de Combate", "imagem":"he_65_maquina_combate.jpg", "comprada":"false"},
            {"id":"he66", "titulo":"Geração X", "imagem":"he_66_geracao_x.jpg", "comprada":"false"},
            {"id":"he67", "titulo":"Os Invasores", "imagem":"he_67_invasores.jpg", "comprada":"false"},
            {"id":"he68", "titulo":"Hulk Vermelho", "imagem":"he_68_hulk_vermelho.jpg", "comprada":"false"},
            {"id":"he69", "titulo":"Garota-Aranha", "imagem":"he_69_garota_aranha.jpg", "original":"What If? (Vol.2) #105; Spider-Girl #1 a 7 (1998/1999)", "comprada":"false"},
            {"id":"he70", "titulo":"Fugitivos", "imagem":"he_70_fugitivos.jpg", "comprada":"false"},
            {"id":"he71", "titulo":"Rocky Racum", "imagem":"he_71_rocky_racum.jpg", "comprada":"false"},
            {"id":"he72", "titulo":"Capitão Bretanha", "imagem":"he_72_capitao_bretanha.jpg", "comprada":"false"},
            {"id":"he73", "titulo":"Os Vingadores da Costa Oeste", "imagem":"he_73_vingadores_costa_oeste.jpg", "comprada":"false"},
            {"id":"he74", "titulo":"O Sentinela", "imagem":"he_74_sentinela.jpg", "comprada":"false"},
            {"id":"he75", "titulo":"Academia de Vingadores", "imagem":"he_75_academia_vingadores.jpg", "comprada":"false"},
            {"id":"he76", "titulo":"Nova", "imagem":"he_76_nova.jpg", "comprada":"false"},
            {"id":"he77", "titulo":"Vingadores Centrais", "imagem":"he_77_vingadores_centrais.jpg", "comprada":"false"},
            {"id":"he78", "titulo":"Mulher-Aranha", "imagem":"he_78_mulher_aranha.jpg", "comprada":"false"},
            {"id":"he79", "titulo":"Jovens Vingadores", "imagem":"he_79_jovens_vingadores.jpg", "comprada":"false"},
            {"id":"he80", "titulo":"Mulher-Hulk", "imagem":"he_80_mulher_hulk.jpg", "comprada":"false"},
            {"id":"he81", "titulo":"Vingadores de Estimação", "imagem":"he_81_vingadores_estimacao.jpg", "comprada":"false"},
            {"id":"he82", "titulo":"Manto & Adaga", "imagem":"he_82_manto_adaga.jpg", "comprada":"false"},
            {"id":"he83", "titulo":"83", "imagem":"", "comprada":"false"},
            {"id":"he84", "titulo":"84", "imagem":"", "comprada":"false"},
            {"id":"he85", "titulo":"85", "imagem":"", "comprada":"false"},
            {"id":"he86", "titulo":"86", "imagem":"", "comprada":"false"},
            {"id":"he87", "titulo":"87", "imagem":"", "comprada":"false"},
            {"id":"he88", "titulo":"88", "imagem":"", "comprada":"false"},
            {"id":"he89", "titulo":"89", "imagem":"", "comprada":"false"},
            {"id":"he90", "titulo":"90", "imagem":"", "comprada":"false"},
            {"id":"he91", "titulo":"91", "imagem":"", "comprada":"false"},
            {"id":"he92", "titulo":"92", "imagem":"", "comprada":"false"},
            {"id":"he93", "titulo":"93", "imagem":"", "comprada":"false"},
            {"id":"he94", "titulo":"94", "imagem":"", "comprada":"false"},
            {"id":"he95", "titulo":"95", "imagem":"", "comprada":"false"},
            {"id":"he96", "titulo":"96", "imagem":"", "comprada":"false"},
            {"id":"he97", "titulo":"97", "imagem":"", "comprada":"false"},
            {"id":"he98", "titulo":"98", "imagem":"", "comprada":"false"},
            {"id":"he99", "titulo":"99", "imagem":"", "comprada":"false"},
            {"id":"he100", "titulo":"100", "imagem":"", "comprada":"false"}
        ]
    },
    {
        "titulo":"homemaranha", "edicoes":
        [
            {"id":"ha01", "titulo":"Caído entre os Mortos", "imagem":"ha_01_caido_entre_mortos.jpg", "comprada":"true", "preco":9.90, "original":"Marvel Knights Spider-Man #1-6 (2004)"},
            {"id":"ha02", "titulo":"Percepções", "imagem":"ha_02_percepcoes.jpg", "comprada":"true", "preco":24.90, "original":"Spider-Man #6-12 (1991)"},
            {"id":"ha03", "titulo":"A Saga Original do Clone", "imagem":"ha_03_saga_original_clone.jpg", "comprada":"true", "preco":39.90, "original":"Amazing Spider-Man #129, 143-150 (1974/75)"},
            {"id":"ha04", "titulo":"O Mal no Coração dos Homens", "imagem":"ha_04_mal_coracao_homens.jpg", "comprada":"true", "preco":39.90, "original":"Spider-Man/Black Cat: The Evil that Men Do #1-6 (2002/2006)"},
            {"id":"ha05", "titulo":"Feroz", "imagem":"ha_05_feroz.jpg", "comprada":"true", "preco":39.90, "original":"Sensational Spider-Man (Vol.2) #23-27 (2006)"},
            {"id":"ha06", "titulo":"Heroi da Resistência", "imagem":"ha_06_heroi_resistencia.jpg", "comprada":"true", "preco":39.90, "original":"Marvel Knights Spider-Man #7-12 (2004/2005)"},
            {"id":"ha07", "titulo":"Tormento", "imagem":"ha_07_tormento.jpg", "comprada":"true", "preco":39.90, "original":"Spider-Man #1-5, Spider-Man #13-14 (1990/91)"},
            {"id":"ha08", "titulo":"A Morte de Jean DeWolff", "imagem":"ha_08_morte_jean_dewolff.jpg", "comprada":"true", "preco":39.90, "original":"Peter Parker, The Spectacular Spider-Man #107-110, #134-136 (1985/86 e 1988)"},
            {"id":"ha09", "titulo":"Com Grandes Poderes...", "imagem":"ha_09_com_grandes_poderes.jpg", "comprada":"true", "preco":39.90, "original":"Spider-Man: With Great Power... #1-5 (2008)"},
            {"id":"ha10", "titulo":"O Fator Mutante", "imagem":"ha_10_fator_mutante.jpg", "comprada":"true", "preço":39.90, "original":"Spider-Man #15-17 (1991), X-Force #4 (1991), Marvel Comics Presents: Wolverine #48-50 (1990)"},
            {"id":"ha11", "titulo":"Potestade", "imagem":"ha_11_potestade.jpg", "comprada":"true", "preço":39.90, "original":"Spider-Man: Reign #1-4 (2006/2007)"},
            {"id":"ha12", "titulo":"Uma Teia Embaraçada", "imagem":"ha_12_teia_embaracada.jpg", "comprada":"true", "preço":39.90, "original":"Spider-Man´s Tangled Web #1-3, #13-15 (2001/2002)"},
            {"id":"ha13", "titulo":"A Vingança do Sexteto Sinistro", "imagem":"ha_13_vinganca_sexteto_sinistro.jpg", "comprada":"true", "preço":39.90, "original":"Spider-Man #18-23 (1992)"},
            {"id":"ha14", "titulo":"O Casamento", "imagem":"ha_14_casamento.jpg", "comprada":"true", "preco":39.90, "original":"The Amazing Spider-Man #290-292 (1987), The Amazing Spider-Man Annual #21 (1987), The Amazing Spider-Man: Parallel Lives (2012)"},
            {"id":"ha15", "titulo":"Homem-Aranha Noir", "imagem":"ha_15_homem_aranha_noir.jpg", "comprada":"true", "preco":39.90, "original":"Spider-Man Noir #1-4, Spider-Man Noir: Eyes Without a Face #1-4"},
            {"id":"ha16", "titulo":"Origens", "imagem":"ha_16_origens.jpg", "comprada":"false", "preco":0, "original":"Amazing Fantasy #15, The Amazing Spider-Man #1-6, The Amazing Spider-Man Annual #1"},
            {"id":"ha17", "titulo":"A Saga do Traje Alienígena", "imagem":"ha_17_saga_traje_alienigena.jpg", "comprada":"false", "preco":0, "original":"The Amazing Spider-Man #252-259 (1984)"},
            {"id":"ha18", "titulo":"O Nascimento de Venom", "imagem":"ha_18_nascimento_venom.jpg", "comprada":"false", "preco":0, "original":"Web of Spider-Man #1, Amazing Spider-Man #298-302"},
            {"id":"ha19", "titulo":"O Outro - Evolução ou Morte - Parte 1", "imagem":"ha_19_outro_evolucao_morte_1.jpg", "comprada":"false", "preco":0, "original":"Friendly Neighborhood Spider-Man #1-2, Marvel Knights Spider-Man #19-20, The Amazing Spider-Man #525-526"},
            {"id":"ha20", "titulo":"O Outro - Evolução ou Morte - Parte 2", "imagem":"ha_20_outro_evolucao_morte_2.jpg", "comprada":"false", "preco":0, "original":"Friendly Neighborhood Spider-Man #3-4, Marvel Knights Spider-Man #21-22, The Amazing Spider-Man #527-528"},
            {"id":"ha21", "titulo":"A Morte da Tia May", "imagem":"ha_21_morte_tia_may.jpg", "comprada":"false", "preco":0, "original":"The Amazing Spider-Man #194-200 (1979/80)"},
            {"id":"ha22", "titulo":"Caça ao Aranha", "imagem":"ha_22_caca_aranha.jpg", "comprada":"false", "preco":0, "original":"Spider-Man #88-89, The Sensational Spider-Man #25, The Amazing Spider-Man #432, The Spectacular Spider-Man #254-255 (1998)"},
            {"id":"ha23", "titulo":"A Volta do Uniforme Negro", "imagem":"ha_23_volta_uniforme_negro.jpg", "comprada":"false", "preco":0, "original":"The Amazing Spider-Man #539-543, The Sensational Spider-Man (Vol.2) #38-40 (2007)"},
            {"id":"ha24", "titulo":"O Rapto de Mary Jane", "imagem":"ha_24_rapto_mary_jane.jpg", "comprada":"false", "preco":0, "original":"The Amazing Spider-Man #303-309"},
            {"id":"ha25", "titulo":"Um Dia a Mais", "imagem":"ha_25_dia_mais.jpg", "comprada":"false", "preco":0, "original":"The Amazing Spider-Man #42-43 (1966), #544-545 (2007), Friendly Neighborhood Spider-Man #24 (2007), The Sensational Spider-Man #41 (2007), Untold Tales of Spider-Man #16 (1996)"},
            {"id":"ha26", "titulo":"Nada Pode Deter o Fanático", "imagem":"ha_26_nada_pode_deter_fanatico.jpg", "comprada":"false", "preco":0, "original":"The Amazing Spider-Man #224-230 (1982)"},
            {"id":"ha27", "titulo":"Um Novo dia", "imagem":"ha-27-novo-dia.jpg", "comprada":"false", "preco":0, "original":"Amazing Spider-Man #546-551 (2008), Free Comic Book Day 2007: Amazing Spider-Man #1"},
            {"id":"ha28", "titulo":"Inferno", "imagem":"ha-28-inferno.jpg", "comprada":"false", "preco":0, "original":"Amazing Spider-Man #310-314, Peter Parker, Spider-Man #146, Web of Spider-Man #47 (1988/1989)"},
            {"id":"ha29", "titulo":"29", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha30", "titulo":"30", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha31", "titulo":"31", "imagem":"ha_31_.jpg", "comprada":"false", "preco":0, "original":""},
            {"id":"ha32", "titulo":"32", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha33", "titulo":"33", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha34", "titulo":"34", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha35", "titulo":"35", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha36", "titulo":"36", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha37", "titulo":"37", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha38", "titulo":"38", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha39", "titulo":"39", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha40", "titulo":"40", "imagem":"ha_40_.jpg", "comprada":"false", "preco":0, "original":""},
            {"id":"ha41", "titulo":"41", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha42", "titulo":"42", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha43", "titulo":"43", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha44", "titulo":"44", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha45", "titulo":"45", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha46", "titulo":"46", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha47", "titulo":"47", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha48", "titulo":"48", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha49", "titulo":"49", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha50", "titulo":"50", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha51", "titulo":"51", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha52", "titulo":"52", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha53", "titulo":"53", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha54", "titulo":"54", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha55", "titulo":"55", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha56", "titulo":"56", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha57", "titulo":"57", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha58", "titulo":"58", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha59", "titulo":"59", "imagem":"", "comprada":"false", "preco":0, "original":""},
            {"id":"ha60", "titulo":"60", "imagem":"", "comprada":"false", "preco":0, "original":""}
        ]
    },
    {
        "titulo":"batman", "edicoes":
        [
            {"id":"ba01", "titulo":"Cataclismo", "imagem":"ba_01_cataclismo.jpg", "comprada":"true", "preco":89.90},
            {"id":"ba02", "titulo":"Terra de Ninguém - Parte 1", "imagem":"ba_02_terra_ninguem_1.jpg", "comprada":"true", "preco":89.90},
            {"id":"ba03", "titulo":"Terra de Ninguém - Parte 2", "imagem":"ba_03_terra_ninguem_2.jpg", "comprada":"true", "preco":89.90},
            {"id":"ba04", "titulo":"Terra de Ninguém - Parte 3", "imagem":"ba_04_terra_ninguem_3.jpg", "comprada":"true", "preco":89.90},
            {"id":"ba05", "titulo":"Terra de Ninguém - Parte 4", "imagem":"ba_05_terra_ninguem_4.jpg", "comprada":"true", "preco":89.90},
            {"id":"ba06", "titulo":"Terra de Ninguém - Parte 5", "imagem":"ba_06_terra_ninguem_5.jpg", "comprada":"true", "preco":0},
        ]
    },
    {
        "titulo":"vagabond", "edicoes":
        [
            {"titulo":"Vagabond 1", "imagem":"vagabond-1.jpg", "comprada":"true"},
            {"titulo":"Vagabond 2", "imagem":"vagabond-2.jpg", "comprada":"true"},
            {"titulo":"Vagabond 3", "imagem":"vagabond-3.jpg", "comprada":"true"},
            {"titulo":"Vagabond 4", "imagem":"vagabond-4.jpg", "comprada":"true"},
            {"titulo":"Vagabond 5", "imagem":"vagabond-5.jpg", "comprada":"true"},
            {"titulo":"Vagabond 6", "imagem":"vagabond-6.jpg", "comprada":"true"},
            {"titulo":"Vagabond 7", "imagem":"vagabond-7.jpg", "comprada":"true"},
            {"titulo":"Vagabond 8", "imagem":"vagabond-8.jpg", "comprada":"true"},
            {"titulo":"Vagabond 9", "imagem":"vagabond-9.jpg", "comprada":"true"},
            {"titulo":"Vagabond 10", "imagem":"vagabond-10.jpg", "comprada":"true"},
            {"titulo":"Vagabond 11", "imagem":"vagabond-11.jpg", "comprada":"true"},
            {"titulo":"Vagabond 12", "imagem":"vagabond-12.jpg", "comprada":"true"},
            {"titulo":"Vagabond 13", "imagem":"vagabond-13.jpg", "comprada":"true"},
            {"titulo":"Vagabond 14", "imagem":"vagabond-14.jpg", "comprada":"true"},
            {"titulo":"Vagabond 15", "imagem":"vagabond-15.jpg", "comprada":"true"},
            {"titulo":"Vagabond 16", "imagem":"vagabond-16.jpg", "comprada":"true"},
            {"titulo":"Vagabond 17", "imagem":"vagabond-17.jpg", "comprada":"true"},
            {"titulo":"Vagabond 18", "imagem":"vagabond-18.jpg", "comprada":"true"},
            {"titulo":"Vagabond 19", "imagem":"vagabond-19.jpg", "comprada":"true"},
            {"titulo":"Vagabond 20", "imagem":"vagabond-20.jpg", "comprada":"true"},
            {"titulo":"Vagabond 21", "imagem":"vagabond-21.jpg", "comprada":"true"},
            {"titulo":"Vagabond 22", "imagem":"vagabond-22.jpg", "comprada":"false"},
            {"titulo":"Vagabond 23", "imagem":"vagabond-23.jpg", "comprada":"false"},
            {"titulo":"Vagabond 24", "imagem":"vagabond-24.jpg", "comprada":"false"},
            {"titulo":"Vagabond 25", "imagem":"vagabond-25.jpg", "comprada":"false"},
            {"titulo":"Vagabond 26", "imagem":"vagabond-26.jpg", "comprada":"false"},
            {"titulo":"Vagabond 27", "imagem":"vagabond-27.jpg", "comprada":"false"},
            {"titulo":"Vagabond 28", "imagem":"vagabond-28.jpg", "comprada":"false"},
            {"titulo":"Vagabond 29", "imagem":"vagabond-29.jpg", "comprada":"false"},
            {"titulo":"Vagabond 30", "imagem":"vagabond-30.jpg", "comprada":"false"}
        ]
    },
    {
        "titulo":"lobosolitario", "edicoes":
        [
            {"titulo":"Lobo Solitário 1", "imagem":"lobo-solitario-1.jpg", "comprada":"true"},
            {"titulo":"Lobo Solitário 2", "imagem":"lobo-solitario-2.jpg", "comprada":"true"},
            {"titulo":"Lobo Solitário 3", "imagem":"lobo-solitario-3.jpg", "comprada":"true"},
            {"titulo":"Lobo Solitário 4", "imagem":"lobo-solitario-4.jpg", "comprada":"true"},
            {"titulo":"Lobo Solitário 5", "imagem":"lobo-solitario-5.jpg", "comprada":"false"},
            {"titulo":"Lobo Solitário 6", "imagem":"lobo-solitario-6.jpg", "comprada":"false"},
            {"titulo":"Lobo Solitário 7", "imagem":"lobo-solitario-7.jpg", "comprada":"false"},
            {"titulo":"Lobo Solitário 8", "imagem":"lobo-solitario-8.jpg", "comprada":"false"},
            {"titulo":"Lobo Solitário 9", "imagem":"lobo-solitario-9.jpg", "comprada":"false"},
            {"titulo":"Lobo Solitário 10", "imagem":"lobo-solitario-10.jpg", "comprada":"false"},
        ]
    },
    {
        "titulo":"novolobo", "edicoes":
        [
            {"titulo":"Novo Lobo Solitário 1", "imagem":"novo-lobo-solitario-1.jpg", "comprada":"true"},
            {"titulo":"Novo Lobo Solitário 2", "imagem":"novo-lobo-solitario-2.jpg", "comprada":"true"},
            {"titulo":"Novo Lobo Solitário 3", "imagem":"novo-lobo-solitario-3.jpg", "comprada":"true"},
            {"titulo":"Novo Lobo Solitário 4", "imagem":"novo-lobo-solitario-4.jpg", "comprada":"true"},
            {"titulo":"Novo Lobo Solitário 5", "imagem":"novo-lobo-solitario-5.jpg", "comprada":"true"},
            {"titulo":"Novo Lobo Solitário 6", "imagem":"novo-lobo-solitario-6.jpg", "comprada":"false"},
            {"titulo":"Novo Lobo Solitário 7", "imagem":"novo-lobo-solitario-7.jpg", "comprada":"false"},
            {"titulo":"Novo Lobo Solitário 8", "imagem":"novo-lobo-solitario-8.jpg", "comprada":"false"},
            {"titulo":"Novo Lobo Solitário 9", "imagem":"novo-lobo-solitario-9.jpg", "comprada":"false"},
            {"titulo":"Novo Lobo Solitário 10", "imagem":"novo-lobo-solitario-10.jpg", "comprada":"false"},
        ]
    },
    {
        "titulo":"valiant", "edicoes":
        [
            {"titulo":"Divinity", "imagem":"valiant-divinity.jpg", "comprada":"true"},
            {"titulo":"Faith", "imagem":"valiant-faith.jpg", "comprada":"false"},
            {"titulo":"Ninjak", "imagem":"valiant-ninjak.jpg", "comprada":"false"},
        ]
    },
    {
        "titulo":"panini", "edicoes":
        [
            {"titulo":"Deadpool - Antologia", "imagem":"panini-deadpool-antologia.jpg", "comprada":"false"},
            {"titulo":"Homem-Aranha - Antologia", "imagem":"panini-homem-aranha-antologia.jpg", "comprada":"false"},
            {"titulo":"Deadpool Massacra o Universo Marvel", "imagem":"panini-deadpool-massacra-universo-marvel.jpg", "comprada":"true"},
            {"titulo":"Deadpool - Meus Queridos Presidentes", "imagem":"panini-deadpool-queridos-presidentes.jpg", "comprada":"true"},
            {"titulo":"Deadpool - Caçador de Almas", "imagem":"panini-deadpool-cacador-almas.jpg", "comprada":"true"},
            {"titulo":"Deadpool - Três Homens em Conflito", "imagem":"panini-deadpool-tres-homens-conflito.jpg", "comprada":"true"},
            {"titulo":"Deadpool - S.H.I.E.L.D.", "imagem":"panini-deadpool-shield.jpg", "comprada":"false"},
            {"titulo":"Homem-Aranha - Negócios de Família", "imagem":"panini-marvel-homem-aranha-negocios-familia.jpg", "comprada":"true"},
            {"titulo":"Homem-Aranha Superior - Sem Saída", "imagem":"panini-homem-aranha-superior-sem-saida.jpg", "comprada":"true"},
            {"titulo":"Homem-Aranha Superior - Mente Conturbada", "imagem":"panini-marvel-homem-aranha-superior-mente-conturbada.jpg", "comprada":"true"},
            {"titulo":"Homem-Aranha Superior - Meu Pior Inimigo", "imagem":"panini-marvel-homem-aranha-superior-meu-pior-inimigo.jpg", "comprada":"true"},
            {"titulo":"Homem-Aranha Superior - Mal Necessário", "imagem":"panini-marvel-homem-aranha-superior-mal-necessario.jpg", "comprada":"true"},
            {"titulo":"Homem-Aranha Superior - Venom Superior", "imagem":"panini-marvel-homem-aranha-superior-venom-superior.jpg", "comprada":"true"},
            {"titulo":"Mulher-Maravilha - Sangue", "imagem":"panini-mulher-maravilha-sangue.jpg", "comprada":"true"},
            {"titulo":"Mulher-Maravilha - Direito de Nacença", "imagem":"panini-mulher-maravilha-direito-nascenca.jpg", "comprada":"true"},
            {"titulo":"Mulher-Maravilha - Força", "imagem":"panini-mulher-maravilha-forca.jpg", "comprada":"true"},
            {"titulo":"Mulher-Maravilha - Guerra", "imagem":"panini-mulher-maravilha-guerra.jpg", "comprada":"true"},
            {"titulo":"Lendas do Universo DC - Mulher-Maravilha - 1", "imagem":"panini-lendas-dc-mulher-maravilha-1.jpg", "comprada":"true"},
            {"titulo":"Lendas do Universo DC - Mulher-Maravilha - 2", "imagem":"panini-lendas-dc-mulher-maravilha-2.jpg", "comprada":"true"},
            {"titulo":"Lendas do Universo DC - Mulher-Maravilha - 3", "imagem":"panini-lendas-dc-mulher-maravilha-3.jpg", "comprada":"true"},
            {"titulo":"Lendas do Universo DC - Mulher-Maravilha - 4", "imagem":"panini-lendas-dc-mulher-maravilha-4.jpg", "comprada":"true"},
            {"titulo":"Star Wars - Qui Gon Jinn - O Lado Sombrio", "imagem":"panini-star-wars-o-lado-sombrio.jpg", "comprada":"true"},
            {"titulo":"Star Wars - Boba Fett - Boba Fett está Morto", "imagem":"panini-star-wars-boba-fett-esta-morto.jpg", "comprada":"true"},
            {"titulo":"Star Wars - Boba Fett - Inimigo do Império", "imagem":"panini-star-wars-boba-fett-inimigo-imperio.jpg", "comprada":"true"},
            {"titulo":"Star Wars - Boba Fett - Laços de Sangue", "imagem":"panini-star-wars-boba-fett-lacos-sangue.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-episodio-i-ameaca-fantasma.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-episodio-ii-ataque-clones.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-episodio-iii-vinganca-sith.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-episodio-iv-nova-esperanca.jpg", "comprada":"true"},
            {"titulo":"Star Wars - Episódio V - O Império Contra-Ataca", "imagem":"panini-star-wars-episodio-v.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-episodio-vi.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-episodio-vii.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-imperio-despedacado-panini.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-livro-1.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-livro-2.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-darth-vader-esquadrao-perdido.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-darth-vader-nono-assassino.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-darth-vader-o-clamor-das-sombras-panini.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-darth-maul-lorde-sith.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-darth-maul-sentenca-morte.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-darth-maul-filho-dathomir.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-skywalker-ataca.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-confronto-lua-contrabandistas.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-darth-vader-vader.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-darth-vader-sombras-segredos.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-princesa-leia.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-queda-vader.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-infinities-uma-nova-esperanca.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-infinities-imperio-contra-ataca.jpg", "comprada":"true"},
            {"titulo":"", "imagem":"panini-star-wars-infinities-retorno-jedi.jpg", "comprada":"false"},
            {"titulo":"Star Wars Legends - Herdeiro do Império", "imagem":"panini-star-wars-herdeiro-imperio.jpg", "comprada":"true"},
            {"titulo":"Star Wars Legends - A Ascensão da Força Sombria", "imagem":"panini-star-wars-ascensao-forca-sombria.jpg", "comprada":"false"},
            {"titulo":"Star Wars Legends - O Último Comando", "imagem":"panini-star-wars-ultimo-comando.jpg", "comprada":"false"},
            {"titulo":"Star Wars Legends - À Sombra de Yavin", "imagem":"panini-star-wars-sombra-yavin.jpg", "comprada":"true"},
            {"titulo":"Star Wars Legends - A Guerra nas Estrelas", "imagem":"panini-star-wars-guerra-estrelas.jpg", "comprada":"false"},
            {"titulo":"Future Quest 1", "imagem":"panini-future-quest-1.jpg", "comprada":"true"},
            {"titulo":"Future Quest 2", "imagem":"panini-future-quest-2.jpg", "comprada":"true"},
            {"titulo":"Flintstones 1", "imagem":"panini-flintstones-1.jpg", "comprada":"true"},
            {"titulo":"Flintstones 2", "imagem":"panini-flintstones-2.jpg", "comprada":"false"},
            {"titulo":"Scooby Apocalipse 1", "imagem":"panini-scooby-apocalipse-1.jpg", "comprada":"false"},
            {"titulo":"Scooby Apocalipse 2", "imagem":"panini-scooby-apocalipse-2.jpg", "comprada":"true"},
            {"titulo":"Samurai 7 #1", "imagem":"samurai-7-1.jpg", "comprada":"true"},
            {"titulo":"Samurai 7 #2", "imagem":"samurai-7-2.jpg", "comprada":"true"},
        ]
    },
    {
        "titulo":"conan", "edicoes":
        [
            {"id":"co01", "titulo":"A Cidadela dos Condenados", "imagem":"co_01_cidadela_condenados.jpg", "comprada":"false"},
            {"id":"co02", "titulo":"A Libertação de Thugra Khotan", "imagem":"co_02_libertacao_thugra_khotan.jpg", "comprada":"false"},
            {"id":"co03", "titulo":"A Maldição da Lua Crescente", "imagem":"co_03_maldicao_lua_crescente.jpg", "comprada":"false"},
            {"id":"co04", "titulo":"O Conquistador", "imagem":"co_04_conquistador.jpg", "comprada":"false"},
        ]
    },
    {
        "titulo":"thewalkingdead", "edicoes":
        [
            {"id":"twd01", "titulo":"Dias Passados", "imagem":"twd-01-dias-passados.jpg", "comprada":"true"},
            {"id":"twd02", "titulo":"Caminhos Percorridos", "imagem":"twd-02-caminhos-percorridos.jpg", "comprada":"true"},
            {"id":"twd03", "titulo":"Segurança Atrás das Grades", "imagem":"twd-03-seguranca-atras-grades.jpg", "comprada":"false"},
            {"id":"twd04", "titulo":"Os Mais Íntimos Desejos", "imagem":"twd-04-mais-intimos-desejos.jpg", "comprada":"false"},
            {"id":"twd05", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd06", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd07", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd08", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd09", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd10", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd11", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd12", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd13", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd14", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd15", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd16", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd17", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd18", "titulo":"", "imagem":"", "comprada":"false"},
            {"id":"twd19", "titulo":"Marcha para Guerra", "imagem":"twd-19-marcha-para-guerra.jpg", "comprada":"true"},
            {"id":"twd20", "titulo":"Guerra Total - Parte 1", "imagem":"twd-20-guerra-total-1.jpg", "comprada":"true"},
            {"id":"twd21", "titulo":"Guerra Total - Parte 2", "imagem":"twd-21-guerra-total-2.jpg", "comprada":"false"},
            {"id":"twd22", "titulo":"Um Novo Começo", "imagem":"twd-22-novo-comeco.jpg", "comprada":"false"},
            {"id":"twd23", "titulo":"23", "imagem":"twd-23-.jpg", "comprada":"false"},
        ]
    },
    {
        "titulo":"eagle-batman", "edicoes":
        [
            {"id":"bt01", "titulo":"Batman e Filho", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt02", "titulo":"Faces da Morte", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt03", "titulo":"Batman - Detetive", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt04", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt05", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt06", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt07", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt08", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt09", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt10", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
            {"id":"bt01", "titulo":"", "imagem":"bt-", "comprada":"false", "preco":0, "original":""},
        ]
    },
];
